# Generated by Django 5.0.1 on 2024-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_category_alter_complaint_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_id',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
