# Generated by Django 5.0.1 on 2024-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_email_remove_complaint_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='student_id',
            field=models.CharField(max_length=10),
        ),
    ]
